import GlobalNav from "@/components/GlobalNav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="[color-scheme:dark]">
      <body className="text-darkColor pt-[4.4rem]">
        <div className="min-w-[20rem]">
          <GlobalNav />
          <section>{children}</section>
          <Footer />
        </div>
      </body>
    </html>
  );
}
